# Task 1: Data Cleaning and Preprocessing

**Objective:** The objective of this project is to clean and prepare the Titanic dataset for further analysis.

Data cleaning is an important step in Data Science because raw datasets may contain missing values, duplicate records, inconsistent column names, and incorrect data types. In this project, I will perform basic preprocessing using Python and Pandas.

Pandas is used to load, manipulate, and clean tabular data. NumPy provides numerical computing functionality. These libraries help perform the data preprocessing steps efficiently.

In [ ]:
import pandas as pd
import numpy as np

The Titanic dataset is loaded into a Pandas DataFrame named `df`. It contains passenger information such as age, gender, ticket class, fare, and survival status. The `head()` function displays the first five rows to help us understand the structure of the dataset.

In [ ]:
import seaborn as sns

df = sns.load_dataset("titanic")

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

This step examines the dataset before cleaning. The `shape` attribute returns the number of rows and columns. The column list shows the available features, `isnull().sum()` counts missing values in each column, and `duplicated().sum()` counts duplicate rows.

In [ ]:
print("Dataset Shape:", df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

Dataset Shape: (891, 15)

Column Names:
['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town', 'alive', 'alone']

Missing Values:
survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

Duplicate Rows:
107

The `drop_duplicates()` function removes rows that are identical across all columns. This helps prevent repeated records from affecting subsequent analysis. The updated shape shows the dataset size after duplicate removal.

In [ ]:
df = df.drop_duplicates()

print("Shape after removing duplicates:", df.shape)

Shape after removing duplicates: (784, 15)

Missing values can reduce data quality and affect analysis. Missing ages are replaced with the median age, which is less sensitive to extreme values than the mean. Missing embarkation categories are replaced with their most frequent values, calculated using the mode.

In [ ]:
print(df.isnull().sum())

survived         0
pclass           0
sex              0
age            106
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           582
embark_town      2
alive            0
alone            0
dtype: int64

Missing values can reduce data quality and affect analysis. Missing ages are replaced with the median age, which is less sensitive to extreme values than the mean. Missing embarkation categories are replaced with their most frequent values, calculated using the mode.

In [ ]:
df["age"] = df["age"].fillna(df["age"].median())
df["embarked"] = df["embarked"].fillna(df["embarked"].mode()[0])
df["embark_town"] = df["embark_town"].fillna(df["embark_town"].mode()[0])

In [ ]:
print(df.isnull().sum())

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
deck           582
embark_town      0
alive            0
alone            0
dtype: int64

This step ensures that numerical columns are stored as numeric values and categorical columns are represented as categories. The `errors="coerce"` option converts invalid numeric values to missing values, which should be checked during the final quality review.

In [ ]:
df["age"] = pd.to_numeric(df["age"], errors="coerce")
df["fare"] = pd.to_numeric(df["fare"], errors="coerce")

In [ ]:
df["sex"] = df["sex"].astype("category")
df["class"] = df["class"].astype("category")

This step ensures that numerical columns are stored as numeric values and categorical columns are represented as categories. The `errors="coerce"` option converts invalid numeric values to missing values, which should be checked during the final quality review.

In [ ]:
df = df.rename(columns={
    "survived": "Survived",
    "pclass": "Passenger_Class",
    "sex": "Gender",
    "age": "Age",
    "fare": "Fare"
})

df.head()

,Survived,Passenger_Class,Gender,Age,sibsp,parch,Fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

The `rename()` function changes selected column names to more readable labels. Clear column names make the dataset easier to understand and work with. Only the specified columns are renamed; the remaining column names stay unchanged.

In [ ]:
print("Final Shape:", df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nData Types:")
print(df.dtypes)

Final Shape: (784, 15)

Missing Values:
Survived             0
Passenger_Class      0
Gender               0
Age                  0
sibsp                0
parch                0
Fare                 0
embarked             0
class                0
who                  0
adult_male           0
deck               582
embark_town          0
alive                0
alone                0
dtype: int64

Duplicate Rows:
0

Data Types:
Survived              int64
Passenger_Class       int64
Gender             category
Age                 float64
sibsp                 int64
parch                 int64
Fare                float64
embarked             object
class              category
who                  object
adult_male             bool
deck               category
embark_town          object
alive                object
alone                  bool
dtype: object

The final validation checks the dataset's dimensions, remaining missing values, duplicate rows, and data types. This helps confirm whether the preprocessing steps were effective and identifies any remaining data-quality issues that may need attention.

In [ ]:
df.to_csv("titanic_cleaned.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

The `to_csv()` function exports the cleaned DataFrame to a CSV file. Setting `index=False` prevents Pandas from adding an extra index column.

## Conclusion
The Titanic dataset was inspected, cleaned, and prepared using Pandas. The preprocessing included duplicate removal, missing-value handling, data-type conversion, and column renaming. The final dataset was exported to CSV for future analysis.